### **What? Numpy is a package in python**
 A collection of pre-written functions, classes, and methods. Which are capable of handling and manipulating data and calculating results.  


**Main feature: Arrays**  
 A type of data structures, which store elements and refer to their values via integer indices.

### **Why? Incredibly computationally stable and efficient**
 **Pandas:** Stores multiple types of data simultaneously.  
 **NumPy:** Works in a lower-level language. Created with C.  
 - Shorter computation times.

### **When?**
 - Compute a lot of values for analysis.
 - Deal with vectors and matrics.
 - import and pre-process data into Python directly.
 - Generating random texts.

### **How?**
**N-D array class = Python's List**  
 - Both store ordered data and we use square brackets to display them.  


**N-D array class**  
 - N-D array class is more useful when computing values beacause operations work element wise. 
 - Functions (Faster than Python functions). e.g *np.function_name(ndarray)*
 - Methods (Faster than Python methods). e.g *ndarray.method_name()*
 - Operations
    - Broadcasting
    - Type casting






### **N-D array**
NumPy is commonly used for its N-D array.  
N-D array = N-Dimentional array. (N = Natural Numbers)

 - *point* 0th dimention.
 - *line* 1st dimention.
 - *plane* 2nd dimention.

**0-D array:** a single data point.  
**1-D array:** a sequence of values.  
**2-D array:** a collection of 1-D sequences.  

### Importing NumPy

In [1]:
import numpy as np

### Using NumPy

In [2]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [4]:
array_b = np.array([[1,2,3],[4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

### NumPy Documentation
Documentation is a collection of instructions about all the functions, methods, and classes within a module and details on how to use them. A sort of user manual.
[Documentation Link](https://numpy.org/doc/stable/)

on ide shortcut for documentation of any function is *shift + tab*

In [6]:
np.mean([1,2,3])

2.0

### A Short history of NumPy
The fundamental package for scientific computing with python. *NumPy = Numeric Python*
- Numeric (compatible with Scipy) fast for smaller arreys.
- Scientific Python = SciPy
- Num Array (not compatible with Scipy) fast for large arrays.
- Additionally, developers needed to swith between Numeric and Num Array.
- thus, *Numeric + Num Array = SciPy Core = Numpy* (compatible with Scipy)

### N-D arrays:
- Originate from the NumPy package.
- A special data type in python.
- Can store multiple numeric values in a sequence.
- Elementwise properties.  



**Elementwise Addition:**  
*array_a = [1,2,3]; array_b = [4,5,6]  
array_a + array_b = [1,2,3] + [4,5,6] = [5,7,9]*


In [7]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [8]:
type(array_a)

numpy.ndarray

array -> name of the function.  
ndarray -> name of the object.  
ndarray = array

In [9]:
print(array_a)

[1 2 3]


Using print function doesn't show 'array' before output.

In [10]:
array_a.shape

(3,)

We have a 1-dimentional array of size 3.

**A 2-dimentional array**

In [12]:
array_b = np.array([[1,2,3],[11,22,33]])
print(array_b)

[[ 1  2  3]
 [11 22 33]]


### Geometric equivalence of arrays:
**1-D array**  
- part of a line.
- Values on a single row(or column).  

**2-D array**
- part of a plain.
- a collection of rows and columns.

In [13]:
type(array_b)

numpy.ndarray

The type is same for both 1D and 2D arrays.

In [14]:
array_b.shape

(2, 3)

This output resembles a table consisting of 2 rows. Each row is an array. Each row has 3 values. Like a 2x3 table.

In [15]:
array_b.shape[0]

2

In [16]:
array_b.shape[1]

3

We get the number of rows and colums from shape attribute by indexing ('0' indicates number of rows and '1' indicates number of columns).

In [17]:
array_c = np.array(12)
print(array_c)

12


In [18]:
type(array_c)

numpy.ndarray

Same goes for 0-D arrays (a data point).

In [19]:
array_c.shape

()

Since a single value does not have any shape or dimentions. It is a point in a N-dimentional space.  
However, a single value can have a shape. If it is in an array.

In [20]:
array_d = np.array([12])
array_d.shape

(1,)

this can be thought as a point in a geometic space.

In [21]:
array_d = np.array([[12]])
array_d.shape

(1, 1)

This is a point in a 2D plane.  
The dimention of an array can be identified by it number of opening and closing braces (*[ ]*).

Thus, **ndarrays** can contain  
- single scalers
- sequence of numbers
- table of values

However their syntex resembels another python datatype *"lists"*


### **Arrays vs Lists**

In [26]:
list_a = [1,2,3,4,5,6]
len(list_a)

6

In [25]:
list_b = [[1,2,3],[4,5,6]]
len(list_b)

2

Lists are defined similarly to ndarrays.  

list_a and list_b are python list objects. list_a have 6 items. Where list_b 
have 2. list_b is a list of lists. which is similar in format of ndarrays.  

We can just plug in lists as inputs of the np.array() function.

In [27]:
array_lb = np.array(list_b)

In [36]:
type(list_b)

list

In [32]:
type(array_lb)


numpy.ndarray

Eventhough the syntex resembles arrays, Python recognizes lists as a seperate datatype.

In [34]:
print(list_b)


[[1, 2, 3], [4, 5, 6]]


In [35]:
print(array_lb)

[[1 2 3]
 [4 5 6]]


Eventhough these variables contain the same data, their outputs vary.

In [37]:
array_lb.shape

(2, 3)

In [40]:
# list_b.shape
len(list_b)

2

Arrays have a shape attribute where lists don't. That explains why the output of lists are in a single line.

In [ ]:
len(list_b[0])

3

We can access the sub lists by indexing.

The biggest difference between lists and arrays are array operations work elementwise where list operations don't. To illustrate this:

In [42]:
list_bs = list_b[0] + list_b[1]
array_lbs = array_lb[0] + array_lb[1]

In [44]:
print(list_bs)
print(array_lbs)

[1, 2, 3, 4, 5, 6]
[5 7 9]


list concatenates the items. where, array performs element wise addition.

In [46]:
# import math
# print(math.sqrt(list_a[1,0]))
np.sqrt(array_lb)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

Element wise operations not possible for lists.